account.default-amount=500
account.transfer-commission=0.02

db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=postgres

hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
